#!/usr/bin/env python3
"""Generate the near-identical Telegram-account shop configs.

The ten TG-account bots share one structure and differ only in branding,
currency and which regions/account types they emphasise. Keeping the source of
truth here means you can regenerate them, tweak all ten at once, or add an
eleventh in seconds. Run:

    python tools/gen_tg_configs.py
"""
from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "config")

HEADER = (
    "# ---------------------------------------------------------------------------\n"
    "# {name} — Telegram-accounts shop\n"
    "# Generated by tools/gen_tg_configs.py. Edit that template, not this file,\n"
    "# if you want to regenerate. Secrets (BOT_TOKEN, PROVIDER_TOKEN,\n"
    "# CRYPTOBOT_TOKEN, ADMIN_IDS) come from the environment / .env — never here.\n"
    "# ---------------------------------------------------------------------------\n"
)

# (slug, name, currency, support, welcome-tagline, [region tags])
SHOPS = [
    ("tg_accounts_01", "TeleStore", "USD", "@telestore_support",
     "Магазин Telegram-аккаунтов: свежие виртуалки, отлежавшиеся и премиум."),
    ("tg_accounts_02", "AccMarket", "USD", "@accmarket_help",
     "Аккаунты Telegram (US/EU) с моментальной выдачей после оплаты."),
    ("tg_accounts_03", "NomerShop", "RUB", "@nomershop_support",
     "Виртуальные аккаунты Telegram RU/UA/KZ. Выдача сразу после оплаты."),
    ("tg_accounts_04", "GramAccounts", "USD", "@gramacc_support",
     "Отлежавшиеся Telegram-аккаунты для рассылок и работы."),
    ("tg_accounts_05", "PremiumTG Hub", "USD", "@premiumtg_support",
     "Аккаунты с Telegram Premium и без спам-блоков."),
    ("tg_accounts_06", "SessionVault", "USD", "@sessionvault_support",
     "TData-сессии и аккаунты Telegram под любые задачи."),
    ("tg_accounts_07", "GlobalTG", "EUR", "@globaltg_support",
     "Telegram-аккаунты стран мира: US, UK, DE, FR и другие."),
    ("tg_accounts_08", "QuickReg", "USD", "@quickreg_support",
     "Свежие виртуальные регистрации Telegram по низкой цене."),
    ("tg_accounts_09", "AgedTelega", "RUB", "@agedtelega_support",
     "Старые (отлежавшиеся) аккаунты Telegram от 2019 года."),
    ("tg_accounts_10", "TeleMarket Pro", "USD", "@telemarket_support",
     "Премиум-аккаунты, сессии и виртуалки в одном магазине."),
]

# Shared catalog skeleton. Prices are placeholders — adjust before selling.
CATALOG = [
    {
        "id": "virtual",
        "title": "Виртуальные аккаунты",
        "emoji": "📱",
        "products": [
            {"sku": "virt_us", "title": "Аккаунт (US) — виртуальный номер", "price": 3.50,
             "description": "Свежая регистрация на виртуальный номер США. Формат выдачи: номер + код входа / TData."},
            {"sku": "virt_eu", "title": "Аккаунт (EU) — виртуальный номер", "price": 4.00,
             "description": "Свежая регистрация на номер ЕС. Выдаётся сразу после оплаты."},
            {"sku": "virt_asia", "title": "Аккаунт (Asia) — виртуальный номер", "price": 2.80,
             "description": "Азиатский регион, бюджетный вариант для массовых задач."},
        ],
    },
    {
        "id": "aged",
        "title": "Отлежавшиеся аккаунты",
        "emoji": "🧊",
        "products": [
            {"sku": "aged_6m", "title": "Аккаунт с отлёжкой 6+ мес.", "price": 6.00,
             "description": "Аккаунт, зарегистрированный более полугода назад. Меньше риск ограничений."},
            {"sku": "aged_1y", "title": "Аккаунт с отлёжкой 1+ год", "price": 9.00,
             "description": "Возраст 1 год и более. Подходит для работы и рассылок."},
        ],
    },
    {
        "id": "premium",
        "title": "Премиум и сессии",
        "emoji": "💎",
        "products": [
            {"sku": "premium_1m", "title": "Аккаунт с Telegram Premium (1 мес.)", "price": 8.50,
             "description": "Аккаунт с активной подпиской Telegram Premium на 1 месяц."},
            {"sku": "session_tdata", "title": "TData-сессия", "price": 5.00,
             "description": "Готовая TData-сессия для входа с ПК. Инструкция прилагается."},
        ],
    },
]


def build(slug, name, currency, support, welcome):
    return {
        "name": name,
        "slug": slug,
        "language": "ru",
        "currency": currency,
        "fulfillment": "digital",
        "support_username": support,
        "token_env": "BOT_TOKEN",
        "admin_env": "ADMIN_IDS",
        "orders_chat_env": "ORDERS_CHAT_ID",
        "welcome": (
            f"👋 Добро пожаловать в <b>{name}</b>!\n\n{welcome}\n\n"
            "✅ Оплата картой или криптовалютой\n"
            "⚡️ Моментальная автоматическая выдача\n"
            "🛡 Замена в случае брака по правилам магазина"
        ),
        "rules": (
            "<b>Правила магазина</b>\n\n"
            "• Товар цифровой — после выдачи возврату не подлежит.\n"
            "• Проверяйте вход в аккаунт сразу после получения.\n"
            "• Брак заменяем в течение 24 часов при наличии доказательств.\n"
            "• Использование аккаунтов — под вашу ответственность и по законам вашей страны."
        ),
        "payments": {
            "telegram_enabled": True,
            "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True,
            "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": False,
            "cod_enabled": False,
        },
        "catalog": CATALOG,
    }


def main():
    os.makedirs(OUT, exist_ok=True)
    for slug, name, currency, support, welcome in SHOPS:
        data = build(slug, name, currency, support, welcome)
        path = os.path.join(OUT, f"{slug}.yaml")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(name=name))
            yaml.safe_dump(data, fh, allow_unicode=True, sort_keys=False, width=100)
        print("wrote", path)


if __name__ == "__main__":
    main()
