#!/usr/bin/env python3
"""Generate 50 more shop configs (bots #51..#100).

Same core; compact catalogs. Mix of account marketplaces, digital
goods/services, food and on-location services.

    python tools/gen_pack2.py
"""
from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "config")

HEADER = (
    "# ---------------------------------------------------------------------------\n"
    "# {name}\n"
    "# Generated by tools/gen_pack2.py. Secrets come from env/.env.\n"
    "# ---------------------------------------------------------------------------\n"
)

RULES_DIGITAL = (
    "<b>Правила магазина</b>\n\n"
    "• Цифровой товар возврату не подлежит после выдачи.\n"
    "• Проверяйте товар сразу после получения.\n"
    "• Брак заменяем по обращению в поддержку."
)


def p(sku, title, price, desc=""):
    return {"sku": sku, "title": title, "price": price, "description": desc}


def cat(cid, title, emoji, products):
    return {"id": cid, "title": title, "emoji": emoji, "products": products}


def _base(slug, name, currency, support):
    return {"name": name, "slug": slug, "language": "ru", "currency": currency,
            "support_username": support, "token_env": "BOT_TOKEN",
            "admin_env": "ADMIN_IDS", "orders_chat_env": "ORDERS_CHAT_ID"}


def _pay_digital():
    return {"telegram_enabled": True, "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True, "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": False, "cod_enabled": False}


def _pay_physical():
    d = _pay_digital()
    d["cod_enabled"] = True
    return d


def digital(slug, name, currency, support, tagline, catalog):
    d = _base(slug, name, currency, support)
    d.update({"fulfillment": "digital",
              "welcome": (f"👋 Добро пожаловать в <b>{name}</b>!\n\n{tagline}\n\n"
                          "✅ Оплата картой или криптовалютой\n"
                          "⚡️ Моментальная автоматическая выдача"),
              "rules": RULES_DIGITAL, "payments": _pay_digital(), "catalog": catalog})
    return d


def physical(slug, name, currency, support, tagline, catalog, note, service=False):
    d = _base(slug, name, currency, support)
    intro = ("🗓 Выберите услугу\n💳 Оплата картой, криптой или на месте\n🚗 Приедем к вам"
             if service else
             "🛒 Соберите заказ в корзину\n💳 Оплата картой, криптой или при получении\n🚚 Доставка")
    d.update({"fulfillment": "physical",
              "welcome": f"👋 <b>{name}</b>\n\n{tagline}\n\n{intro}",
              "rules": ("<b>Как это работает</b>\n\n"
                        "1. Выберите позиции и добавьте в корзину.\n"
                        "2. Оформите заказ и укажите адрес.\n"
                        "3. Выберите оплату онлайн или на месте.\n"
                        "4. Мы подтвердим и приедем к вам."),
              "delivery_note": note, "payments": _pay_physical(), "catalog": catalog})
    return d


def account_shop(slug, name, currency, support, what, tagline,
                 price_fresh, price_aged, price_premium):
    """Account marketplace: fresh / aged / premium — same shape as the TG bots."""
    return digital(slug, name, currency, support, tagline, [
        cat("fresh", "Свежие", "🆕", [
            p(f"{slug}_fresh", f"{what} — свежий", price_fresh, "Новый аккаунт, выдача после оплаты."),
        ]),
        cat("aged", "Отлежавшиеся", "🧊", [
            p(f"{slug}_aged", f"{what} — с отлёжкой", price_aged, "Возраст 6+ мес., меньше ограничений."),
        ]),
        cat("premium", "Премиум", "💎", [
            p(f"{slug}_premium", f"{what} — премиум", price_premium, "С доп. верификацией/историей."),
        ]),
    ])


SHOPS = [
    # ---------------- account marketplaces (10) ----------------
    account_shop("whatsapp_accounts", "WhatStore", "USD", "@whatstore_support",
                 "WhatsApp-аккаунт", "Аккаунты WhatsApp для работы и рассылок.", 2.0, 4.0, 7.0),
    account_shop("instagram_accounts", "InstaMarket", "USD", "@instamarket_support",
                 "Instagram-аккаунт", "Аккаунты Instagram для продвижения.", 1.5, 4.0, 9.0),
    account_shop("google_accounts", "MailAccShop", "USD", "@mailacc_support",
                 "Google-аккаунт", "Google/Gmail аккаунты под задачи.", 1.0, 3.0, 6.0),
    account_shop("steam_accounts", "SteamVault", "USD", "@steamvault_support",
                 "Steam-аккаунт", "Игровые аккаунты Steam.", 3.0, 8.0, 20.0),
    account_shop("discord_accounts", "DiscordMarket", "USD", "@discordmarket_support",
                 "Discord-аккаунт", "Аккаунты Discord для серверов и работы.", 1.0, 2.5, 5.0),
    account_shop("minecraft_accounts", "MineShop", "USD", "@mineshop_support",
                 "Minecraft-аккаунт", "Аккаунты Minecraft (Java/Bedrock).", 4.0, 7.0, 12.0),
    account_shop("roblox_accounts", "RobloxMarket", "USD", "@robloxmarket_support",
                 "Roblox-аккаунт", "Аккаунты Roblox с балансом/предметами.", 2.0, 5.0, 15.0),
    account_shop("tiktok_accounts", "TikMarket", "USD", "@tikmarket_support",
                 "TikTok-аккаунт", "Аккаунты TikTok для продвижения.", 1.5, 4.0, 10.0),
    account_shop("twitter_accounts", "XMarket", "USD", "@xmarket_support",
                 "X (Twitter)-аккаунт", "Аккаунты X/Twitter для работы.", 1.5, 4.0, 12.0),
    account_shop("linkedin_accounts", "LinkStore", "USD", "@linkstore_support",
                 "LinkedIn-аккаунт", "Аккаунты LinkedIn для нетворкинга.", 3.0, 6.0, 14.0),

    # ---------------- digital goods & services (25) ----------------
    digital("cloud_gaming", "CloudPlay", "USD", "@cloudplay_support",
            "Облачный гейминг: играй без мощного ПК.", [
        cat("plans", "Подписки", "🎮", [
            p("cg_1m", "Cloud Gaming (1 мес.)", 8.0, "Доступ на месяц, выдача ключа."),
            p("cg_3m", "Cloud Gaming (3 мес.)", 20.0, "Экономия."),
        ])]),
    digital("online_tutoring", "LessonGo", "USD", "@lessongo_support",
            "Онлайн-занятия с репетиторами.", [
        cat("lessons", "Занятия", "🎓", [
            p("lesson_1", "Урок (60 мин)", 15.0, "Доступ/ссылка на занятие в выдаче."),
            p("lesson_5", "Пакет 5 уроков", 65.0, ""),
        ])]),
    digital("webinar_access", "WebinarHub", "USD", "@webinarhub_support",
            "Доступ к вебинарам и записям.", [
        cat("access", "Доступы", "📡", [
            p("web_live", "Живой вебинар", 12.0, "Ссылка на подключение."),
            p("web_record", "Запись + материалы", 8.0, ""),
        ])]),
    digital("netflix_gift", "StreamCards", "USD", "@streamcards_support",
            "Подарочные карты стриминга.", [
        cat("cards", "Карты", "🎬", [
            p("stream_15", "Стриминг — $15", 15.0, "Код пополнения."),
            p("stream_30", "Стриминг — $30", 30.0, ""),
        ])]),
    digital("spotify_gift", "MusicCards", "USD", "@musiccards_support",
            "Подарочные карты музыкальных сервисов.", [
        cat("cards", "Карты", "🎧", [
            p("music_10", "Музыка — $10", 10.0, "Код пополнения."),
            p("music_30", "Музыка — $30", 30.0, ""),
        ])]),
    digital("logo_design", "LogoLab", "USD", "@logolab_support",
            "Дизайн логотипа под ключ.", [
        cat("logo", "Логотипы", "✏️", [
            p("logo_basic", "Логотип Basic", 25.0, "1 концепт, исходники."),
            p("logo_pro", "Логотип Pro", 60.0, "3 концепта, брендбук-лайт."),
        ])]),
    digital("copywriting", "TextCraft", "USD", "@textcraft_support",
            "Тексты и копирайтинг.", [
        cat("texts", "Тексты", "📝", [
            p("text_post", "Пост для соцсетей", 5.0, ""),
            p("text_landing", "Текст для лендинга", 30.0, ""),
        ])]),
    digital("translation", "LinguaGo", "USD", "@linguago_support",
            "Перевод текстов и документов.", [
        cat("translate", "Перевод", "🌍", [
            p("tr_page", "Перевод (1 страница)", 4.0, ""),
            p("tr_doc", "Перевод документа", 20.0, ""),
        ])]),
    digital("video_editing", "CutStudio", "USD", "@cutstudio_support",
            "Монтаж видео для соцсетей и YouTube.", [
        cat("edit", "Монтаж", "🎞", [
            p("edit_reel", "Reels/Shorts (до 60 сек)", 12.0, ""),
            p("edit_long", "Видео до 10 мин", 45.0, ""),
        ])]),
    digital("voiceover", "VoiceLab", "USD", "@voicelab_support",
            "Озвучка и дикторский голос.", [
        cat("voice", "Озвучка", "🎙", [
            p("vo_short", "Озвучка до 1 мин", 8.0, ""),
            p("vo_long", "Озвучка до 5 мин", 30.0, ""),
        ])]),
    digital("resume_writing", "CVForge", "USD", "@cvforge_support",
            "Резюме и сопроводительные письма.", [
        cat("cv", "Резюме", "📄", [
            p("cv_basic", "Резюме Basic", 15.0, ""),
            p("cv_pro", "Резюме + письмо", 30.0, ""),
        ])]),
    digital("wallpapers", "WallShop", "USD", "@wallshop_support",
            "Обои для телефона и рабочего стола.", [
        cat("packs", "Наборы", "🖼", [
            p("wall_phone", "Пак обоев (телефон)", 3.0, "50 обоев 4K."),
            p("wall_desktop", "Пак обоев (десктоп)", 4.0, ""),
        ])]),
    digital("luts", "ColorLUT", "USD", "@colorlut_support",
            "LUT-профили для цветокоррекции.", [
        cat("luts", "LUT-паки", "🎨", [
            p("lut_cinema", "Cinematic LUTs", 9.0, "20 LUT для видео."),
            p("lut_film", "Film Emulation LUTs", 9.0, ""),
        ])]),
    digital("sound_effects", "SFXBox", "USD", "@sfxbox_support",
            "Звуковые эффекты и фоны.", [
        cat("sfx", "Звуки", "🔊", [
            p("sfx_pack", "SFX-пак", 6.0, "200 роялти-фри звуков."),
            p("sfx_ambient", "Эмбиент-фоны", 6.0, ""),
        ])]),
    digital("ringtones", "RingShop", "USD", "@ringshop_support",
            "Рингтоны и мелодии.", [
        cat("tones", "Рингтоны", "🔔", [
            p("ring_pack", "Пак рингтонов", 2.0, "30 мелодий."),
        ])]),
    digital("sticker_packs", "StickerLab", "USD", "@stickerlab_support",
            "Стикер-паки для Telegram.", [
        cat("stickers", "Стикеры", "🧩", [
            p("stk_pack", "Стикер-пак (30 шт.)", 4.0, "Готовый набор + установка."),
            p("stk_custom", "Кастомный стикер-пак", 15.0, ""),
        ])]),
    digital("ai_avatars", "AvatarAI", "USD", "@avatarai_support",
            "AI-аватары и портреты.", [
        cat("avatars", "Аватары", "🧑‍🎨", [
            p("ava_pack", "Пакет 20 аватаров", 6.0, "Загрузите фото — получите набор."),
        ])]),
    digital("ebook_templates", "BookKit", "USD", "@bookkit_support",
            "Шаблоны электронных книг.", [
        cat("templates", "Шаблоны", "📘", [
            p("ebook_tpl", "Шаблон ebook (Canva)", 7.0, ""),
        ])]),
    digital("cv_templates", "CVKit", "USD", "@cvkit_support",
            "Шаблоны резюме.", [
        cat("templates", "Шаблоны", "🗂", [
            p("cvtpl_modern", "Шаблон резюме Modern", 4.0, ""),
            p("cvtpl_bundle", "Набор 10 шаблонов", 15.0, ""),
        ])]),
    digital("social_templates", "PostKit", "USD", "@postkit_support",
            "Шаблоны постов для соцсетей.", [
        cat("templates", "Шаблоны", "📱", [
            p("post_pack", "Пак шаблонов постов", 8.0, "50 шаблонов Canva."),
        ])]),
    digital("email_templates", "MailKit", "USD", "@mailkit_support",
            "Шаблоны email-рассылок.", [
        cat("templates", "Шаблоны", "✉️", [
            p("mailtpl_pack", "Набор email-шаблонов", 10.0, "HTML, адаптивные."),
        ])]),
    digital("crm_access", "CRMBox", "USD", "@crmbox_support",
            "Доступ к CRM-системе.", [
        cat("plans", "Тарифы", "📊", [
            p("crm_1m", "CRM (1 мес.)", 9.0, "Доступ на месяц."),
        ])]),
    digital("proxy_mobile", "MobileProxy", "USD", "@mobileproxy_support",
            "Мобильные прокси с ротацией IP.", [
        cat("mobile", "Мобильные", "📶", [
            p("mproxy_1", "Мобильный прокси (1 шт., 7 дн.)", 8.0, ""),
            p("mproxy_30", "Мобильный прокси (30 дн.)", 25.0, ""),
        ])]),
    digital("game_hosting", "CraftHost", "USD", "@crafthost_support",
            "Хостинг игровых серверов.", [
        cat("servers", "Серверы", "🖧", [
            p("gh_small", "Игровой сервер S (1 мес.)", 5.0, "До 10 игроков."),
            p("gh_large", "Игровой сервер L (1 мес.)", 12.0, ""),
        ])]),
    digital("premium_domains", "DomainVault", "USD", "@domainvault_support",
            "Премиальные и короткие домены.", [
        cat("domains", "Домены", "🏷", [
            p("pdom_short", "Короткий домен", 90.0, "Продаётся один раз."),
            p("pdom_brand", "Брендовый домен", 250.0, ""),
        ])]),

    # ---------------- food / physical (8) ----------------
    physical("sushi", "SushiTime", "RUB", "@sushitime_support",
             "Суши и роллы с доставкой.", [
        cat("sushi", "Суши", "🍣", [
            p("nigiri_salmon", "Нигири с лососем (2 шт.)", 180, ""),
            p("gunkan", "Гункан (2 шт.)", 160, ""),
        ]),
        cat("sets", "Сеты", "🎁", [p("set_sushi", "Суши-сет (30 шт.)", 990, "")]),
    ], note="Доставка 45–75 минут. Минимальный заказ — 700 ₽."),
    physical("burgers", "BurgerHouse", "RUB", "@burgerhouse_support",
             "Бургеры на гриле с доставкой.", [
        cat("burgers", "Бургеры", "🍔", [
            p("burger_beef", "Чизбургер", 320, ""),
            p("burger_double", "Двойной бургер", 420, ""),
        ]),
        cat("sides", "Закуски", "🍟", [p("fries2", "Картофель фри", 130, "")]),
    ], note="Доставка 40–70 минут."),
    physical("shawarma", "ShawarmaGo", "RUB", "@shawarmago_support",
             "Шаурма и донеры с доставкой.", [
        cat("shawarma", "Шаурма", "🌯", [
            p("shawarma_chicken", "Шаурма с курицей", 250, ""),
            p("shawarma_beef", "Шаурма с говядиной", 300, ""),
        ])], note="Доставка 30–60 минут."),
    physical("wok", "WokBox", "RUB", "@wokbox_support",
             "Азиатский вок в коробочках.", [
        cat("wok", "Вок", "🍜", [
            p("wok_chicken", "Вок с курицей", 320, ""),
            p("wok_shrimp", "Вок с креветками", 420, ""),
        ])], note="Доставка 40–70 минут."),
    physical("icecream", "IceCreamGo", "RUB", "@icecreamgo_support",
             "Мороженое и десерты к двери.", [
        cat("icecream", "Мороженое", "🍦", [
            p("ic_cup", "Мороженое (стакан)", 150, ""),
            p("ic_box", "Набор мороженого", 600, ""),
        ])], note="Доставка в термосумке, 30–60 минут."),
    physical("bbq", "GrillHouse", "RUB", "@grillhouse_support",
             "Шашлык и гриль с доставкой.", [
        cat("bbq", "Гриль", "🍢", [
            p("kebab_pork", "Шашлык свиной (300 г)", 450, ""),
            p("kebab_chicken", "Шашлык куриный (300 г)", 380, ""),
        ])], note="Доставка 50–90 минут."),
    physical("tea", "TeaHouse", "RUB", "@teahouse_support",
             "Чай, кофе и сладости.", [
        cat("tea", "Чай", "🍵", [
            p("tea_black", "Чёрный чай (чайник)", 250, ""),
            p("tea_herbal", "Травяной чай", 280, ""),
        ])], note="Доставка по центру, 30–60 минут."),
    physical("plants", "PlantShop", "RUB", "@plantshop_support",
             "Комнатные растения с доставкой.", [
        cat("plants", "Растения", "🪴", [
            p("plant_succulent", "Суккулент", 500, ""),
            p("plant_monstera", "Монстера", 1500, ""),
        ]),
        cat("care", "Уход", "🌱", [p("soil", "Грунт + горшок", 400, "")]),
    ], note="Бережная доставка. Фото растения перед отправкой."),

    # ---------------- on-location services (7) ----------------
    physical("massage", "MassageBook", "RUB", "@massagebook_support",
             "Выездной массаж у вас дома.", [
        cat("services", "Услуги", "💆", [
            p("massage_relax", "Релакс-массаж (60 мин)", 2500, ""),
            p("massage_back", "Массаж спины (30 мин)", 1500, ""),
        ])], note="Мастер приедет со всем необходимым.", service=True),
    physical("nails", "NailBook", "RUB", "@nailbook_support",
             "Маникюр на выезде.", [
        cat("services", "Услуги", "💅", [
            p("nails_manicure", "Маникюр с покрытием", 1800, ""),
            p("nails_pedicure", "Педикюр", 2200, ""),
        ])], note="Выезд мастера к вам.", service=True),
    physical("brows", "BrowBar", "RUB", "@browbar_support",
             "Брови и ресницы на выезде.", [
        cat("services", "Услуги", "👁", [
            p("brows_shape", "Коррекция бровей", 900, ""),
            p("brows_lami", "Ламинирование бровей", 2000, ""),
        ])], note="Мастер приедет к вам.", service=True),
    physical("photographer", "PhotoBook", "RUB", "@photobook_support",
             "Фотосессии по записи.", [
        cat("services", "Услуги", "📸", [
            p("photo_1h", "Фотосессия (1 час)", 4000, "20 обработанных фото."),
            p("photo_event", "Съёмка мероприятия", 12000, ""),
        ])], note="Согласуем локацию и время.", service=True),
    physical("laundry", "LaundryGo", "RUB", "@laundrygo_support",
             "Стирка и химчистка с забором.", [
        cat("services", "Услуги", "🧺", [
            p("laundry_wash", "Стирка (за кг)", 200, ""),
            p("laundry_dry", "Химчистка вещи", 700, ""),
        ])], note="Заберём и привезём обратно.", service=True),
    physical("courier", "CourierGo", "RUB", "@couriergo_support",
             "Курьерская доставка по городу.", [
        cat("services", "Услуги", "🛵", [
            p("courier_city", "Доставка по городу", 300, "До 5 кг."),
            p("courier_express", "Экспресс-доставка", 500, ""),
        ])], note="Укажите адреса забора и доставки в комментарии.", service=True),
    physical("cleaning_car", "AutoDetail", "RUB", "@autodetail_support",
             "Детейлинг и химчистка авто на выезде.", [
        cat("services", "Услуги", "🚙", [
            p("detail_interior", "Химчистка салона", 3500, ""),
            p("detail_polish", "Полировка кузова", 5000, ""),
        ])], note="Нужна парковка и доступ к розетке.", service=True),
]


def main():
    os.makedirs(OUT, exist_ok=True)
    for data in SHOPS:
        path = os.path.join(OUT, f"{data['slug']}.yaml")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(name=data["name"]))
            yaml.safe_dump(data, fh, allow_unicode=True, sort_keys=False, width=100)
    print(f"wrote {len(SHOPS)} configs")


if __name__ == "__main__":
    main()
