#!/usr/bin/env python3
"""Generate the distinct-domain bots (food delivery + digital-goods shops).

These reuse the exact same core as the TG-account bots; only the catalog,
fulfillment type and branding change. Run:

    python tools/gen_domain_configs.py
"""
from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "config")

HEADER = (
    "# ---------------------------------------------------------------------------\n"
    "# {name}\n"
    "# Generated by tools/gen_domain_configs.py. Secrets come from the\n"
    "# environment / .env (BOT_TOKEN, PROVIDER_TOKEN, CRYPTOBOT_TOKEN, ADMIN_IDS).\n"
    "# ---------------------------------------------------------------------------\n"
)

RULES_DIGITAL = (
    "<b>Правила магазина</b>\n\n"
    "• Цифровой товар возврату не подлежит после выдачи.\n"
    "• Проверяйте товар сразу после получения.\n"
    "• Брак заменяем по обращению в поддержку.\n"
    "• Покупая товар, вы соглашаетесь с правилами."
)


def digital(slug, name, currency, support, tagline, catalog, testnet=False):
    return {
        "name": name, "slug": slug, "language": "ru", "currency": currency,
        "fulfillment": "digital", "support_username": support,
        "token_env": "BOT_TOKEN", "admin_env": "ADMIN_IDS",
        "orders_chat_env": "ORDERS_CHAT_ID",
        "welcome": (
            f"👋 Добро пожаловать в <b>{name}</b>!\n\n{tagline}\n\n"
            "✅ Оплата картой или криптовалютой\n"
            "⚡️ Моментальная автоматическая выдача"
        ),
        "rules": RULES_DIGITAL,
        "payments": {
            "telegram_enabled": True, "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True, "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": testnet, "cod_enabled": False,
        },
        "catalog": catalog,
    }


def physical(slug, name, currency, support, tagline, catalog, delivery_note):
    return {
        "name": name, "slug": slug, "language": "ru", "currency": currency,
        "fulfillment": "physical", "support_username": support,
        "token_env": "BOT_TOKEN", "admin_env": "ADMIN_IDS",
        "orders_chat_env": "ORDERS_CHAT_ID",
        "welcome": (
            f"👋 <b>{name}</b>\n\n{tagline}\n\n"
            "🛒 Соберите заказ в корзину\n"
            "💳 Оплата картой, криптой или при получении\n"
            "🚚 Доставка по городу"
        ),
        "rules": (
            "<b>Как это работает</b>\n\n"
            "1. Добавьте блюда в корзину.\n"
            "2. Оформите заказ и укажите адрес.\n"
            "3. Выберите оплату онлайн или при получении.\n"
            "4. Мы подтвердим заказ и привезём его вам."
        ),
        "delivery_note": delivery_note,
        "payments": {
            "telegram_enabled": True, "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True, "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": False, "cod_enabled": True,
        },
        "catalog": catalog,
    }


def p(sku, title, price, desc=""):
    return {"sku": sku, "title": title, "price": price, "description": desc}


def cat(cid, title, emoji, products):
    return {"id": cid, "title": title, "emoji": emoji, "products": products}


SHOPS = [
    # ---------------- food delivery (physical) ----------------
    physical(
        "food_rolls", "RollBox — роллы и фастфуд", "RUB", "@rollbox_support",
        "Роллы, суши-сеты и фастфуд с доставкой. Свежесть и скорость.",
        [
            cat("rolls", "Роллы", "🍣", [
                p("roll_phil", "Филадельфия", 380, "Лосось, сливочный сыр, огурец. 8 шт."),
                p("roll_cali", "Калифорния", 320, "Краб, авокадо, икра тобико. 8 шт."),
                p("roll_unagi", "Унаги маки", 300, "Копчёный угорь, соус унаги. 8 шт."),
            ]),
            cat("sets", "Сеты", "🎁", [
                p("set_family", "Сет «Семейный»", 1290, "40 шт. ассорти популярных роллов."),
                p("set_mini", "Сет «Мини»", 650, "16 шт. для одного-двух человек."),
            ]),
            cat("fastfood", "Фастфуд", "🍔", [
                p("burger_classic", "Бургер классический", 290, "Котлета из говядины, сыр, соус."),
                p("fries", "Картофель фри", 130, "Хрустящий, с солью."),
                p("nuggets", "Наггетсы (9 шт.)", 220, "Куриные наггетсы с соусом на выбор."),
            ]),
            cat("drinks", "Напитки", "🥤", [
                p("cola", "Cola 0.5", 120, "Классическая газировка."),
                p("water", "Вода 0.5", 70, "Негазированная."),
            ]),
        ],
        delivery_note="Доставка 60–90 минут. Минимальный заказ — 700 ₽.",
    ),

    # ---------------- my pick: VPN subscriptions ----------------
    digital(
        "vpn", "SwiftVPN", "USD", "@swiftvpn_support",
        "Быстрый и безопасный VPN. Ключ приходит сразу после оплаты.",
        [
            cat("plans", "Подписки", "🔐", [
                p("vpn_1m", "VPN — 1 месяц", 3.00, "Доступ на 1 месяц, до 5 устройств. Выдаётся ключ/конфиг."),
                p("vpn_3m", "VPN — 3 месяца", 8.00, "3 месяца доступа, экономия 10%."),
                p("vpn_12m", "VPN — 1 год", 25.00, "Год доступа, лучшая цена."),
            ]),
            cat("dedicated", "Персональные", "⭐️", [
                p("vpn_dedic", "Выделенный IP (1 мес.)", 7.00, "Личный статический IP для стабильной работы."),
            ]),
        ],
    ),

    # ---------------- proxies ----------------
    digital(
        "proxies", "ProxyHub", "USD", "@proxyhub_support",
        "Приватные и резидентные прокси для любых задач.",
        [
            cat("datacenter", "Датацентр", "🖥", [
                p("proxy_ipv4", "IPv4 прокси (1 шт., 30 дн.)", 2.00, "Приватный IPv4, HTTP/SOCKS5."),
                p("proxy_ipv6", "IPv6 прокси (10 шт., 30 дн.)", 3.00, "Пакет IPv6 для массовых задач."),
            ]),
            cat("residential", "Резидентные", "🏠", [
                p("proxy_res_1gb", "Резидентные — 1 ГБ", 4.50, "Ротация IP, оплата за трафик."),
                p("proxy_res_5gb", "Резидентные — 5 ГБ", 20.00, "Пакет 5 ГБ со скидкой."),
            ]),
        ],
    ),

    # ---------------- gift cards ----------------
    digital(
        "giftcards", "GiftZone", "USD", "@giftzone_support",
        "Подарочные карты и коды пополнения популярных сервисов.",
        [
            cat("stores", "Магазины", "🛍", [
                p("gc_amazon_25", "Amazon — $25", 24.00, "Код подарочной карты Amazon на $25."),
                p("gc_steam_20", "Steam — $20", 19.50, "Код пополнения кошелька Steam на $20."),
            ]),
            cat("mobile", "Мобильные", "📱", [
                p("gc_appstore_15", "App Store / iTunes — $15", 14.50, "Код пополнения Apple на $15."),
                p("gc_google_15", "Google Play — $15", 14.50, "Код пополнения Google Play на $15."),
            ]),
        ],
    ),

    # ---------------- software keys ----------------
    digital(
        "software_keys", "KeyMarket", "USD", "@keymarket_support",
        "Лицензионные ключи для ПО и операционных систем.",
        [
            cat("os", "Операционные системы", "🪟", [
                p("key_win11pro", "Windows 11 Pro", 12.00, "Лицензионный ключ активации Windows 11 Pro."),
                p("key_win10pro", "Windows 10 Pro", 10.00, "Лицензионный ключ активации Windows 10 Pro."),
            ]),
            cat("office", "Офис и утилиты", "📊", [
                p("key_office2021", "Office 2021 Pro Plus", 18.00, "Ключ активации Microsoft Office 2021."),
                p("key_antivirus", "Антивирус (1 год)", 9.00, "Годовая лицензия популярного антивируса."),
            ]),
        ],
    ),

    # ---------------- eSIM / virtual numbers ----------------
    digital(
        "esim", "eSIM Go", "EUR", "@esimgo_support",
        "eSIM для путешествий и виртуальные номера для регистраций.",
        [
            cat("travel", "eSIM для поездок", "✈️", [
                p("esim_eu_5gb", "Европа — 5 ГБ / 30 дн.", 12.00, "eSIM с интернетом по Европе."),
                p("esim_global_3gb", "Мир — 3 ГБ / 15 дн.", 15.00, "Глобальный роуминг-пакет."),
            ]),
            cat("numbers", "Виртуальные номера", "☎️", [
                p("num_sms", "Номер для SMS (разовый)", 1.00, "Одноразовый номер для приёма кода."),
                p("num_rent", "Аренда номера (7 дн.)", 5.00, "Номер в аренду на неделю."),
            ]),
        ],
    ),

    # ---------------- hosting / VPS reseller ----------------
    digital(
        "hosting", "CloudNode", "USD", "@cloudnode_support",
        "VPS и хостинг с моментальной выдачей доступов.",
        [
            cat("vps", "VPS", "🖥", [
                p("vps_start", "VPS Start (1 vCPU / 1 ГБ)", 4.00, "1 vCPU, 1 ГБ RAM, 20 ГБ SSD. Данные доступа в выдаче."),
                p("vps_pro", "VPS Pro (2 vCPU / 4 ГБ)", 10.00, "2 vCPU, 4 ГБ RAM, 60 ГБ SSD."),
            ]),
            cat("web", "Веб-хостинг", "🌐", [
                p("host_basic", "Хостинг Basic (1 мес.)", 2.50, "10 ГБ, 1 сайт, SSL."),
                p("host_business", "Хостинг Business (1 мес.)", 6.00, "50 ГБ, безлимит сайтов, SSL."),
            ]),
        ],
    ),

    # ---------------- online courses / ebooks ----------------
    digital(
        "courses", "SkillShop", "USD", "@skillshop_support",
        "Онлайн-курсы и электронные книги. Доступ приходит сразу.",
        [
            cat("courses", "Курсы", "🎓", [
                p("course_python", "Курс «Python с нуля»", 15.00, "Видеокурс + материалы. Ссылка на доступ в выдаче."),
                p("course_smm", "Курс «SMM-специалист»", 20.00, "Полный курс по продвижению в соцсетях."),
            ]),
            cat("ebooks", "Электронные книги", "📚", [
                p("ebook_finance", "Книга «Личные финансы»", 5.00, "PDF/EPUB, мгновенная выдача ссылки."),
                p("ebook_marketing", "Книга «Маркетинг 101»", 5.00, "Основы маркетинга для начинающих."),
            ]),
        ],
    ),

    # ---------------- design templates / services ----------------
    digital(
        "design", "PixelMarket", "USD", "@pixelmarket_support",
        "Готовые дизайн-шаблоны и цифровые ассеты.",
        [
            cat("templates", "Шаблоны", "🎨", [
                p("tpl_logo", "Пакет логотипов (10 шт.)", 8.00, "Редактируемые исходники в векторе."),
                p("tpl_presentation", "Шаблон презентации", 6.00, "Готовый шаблон для PowerPoint/Keynote."),
            ]),
            cat("assets", "Ассеты", "🧩", [
                p("asset_icons", "Набор иконок (200 шт.)", 5.00, "SVG/PNG набор иконок для интерфейсов."),
                p("asset_ui_kit", "UI-kit для приложения", 12.00, "Компоненты интерфейса, Figma."),
            ]),
        ],
    ),

    # ---------------- game keys ----------------
    digital(
        "game_keys", "GameVault", "USD", "@gamevault_support",
        "Ключи для игр и пополнение игровых кошельков.",
        [
            cat("games", "Игры", "🎮", [
                p("game_key_aaa", "Ключ AAA-игры (Steam)", 25.00, "Ключ активации в Steam для новинки."),
                p("game_key_indie", "Ключ инди-игры", 8.00, "Ключ активации популярной инди-игры."),
            ]),
            cat("topup", "Пополнения", "💰", [
                p("topup_steam_10", "Steam кошелёк — $10", 10.00, "Код пополнения Steam на $10."),
                p("topup_ps_10", "PlayStation — $10", 10.00, "Код пополнения PSN на $10."),
            ]),
        ],
    ),
]


def main():
    os.makedirs(OUT, exist_ok=True)
    for data in SHOPS:
        path = os.path.join(OUT, f"{data['slug']}.yaml")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(name=data["name"]))
            yaml.safe_dump(data, fh, allow_unicode=True, sort_keys=False, width=100)
        print("wrote", path)


if __name__ == "__main__":
    main()
