#!/usr/bin/env python3
"""Generate 30 extra niche shop configs (bots #21..#50).

Same core, only catalog/branding/fulfilment differ. Digital shops deliver from
stock instantly; physical shops collect an address and support pay-on-delivery.
The three on-location services (mobile barber, cleaning, mobile car wash) use
the physical flow — the address step is where the master comes to you.

    python tools/gen_niche_configs.py
"""
from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "config")

HEADER = (
    "# ---------------------------------------------------------------------------\n"
    "# {name}\n"
    "# Generated by tools/gen_niche_configs.py. Secrets come from the environment\n"
    "# / .env (BOT_TOKEN, PROVIDER_TOKEN, CRYPTOBOT_TOKEN, ADMIN_IDS).\n"
    "# ---------------------------------------------------------------------------\n"
)

RULES_DIGITAL = (
    "<b>Правила магазина</b>\n\n"
    "• Цифровой товар возврату не подлежит после выдачи.\n"
    "• Проверяйте товар сразу после получения.\n"
    "• Брак заменяем по обращению в поддержку."
)


def p(sku, title, price, desc=""):
    return {"sku": sku, "title": title, "price": price, "description": desc}


def cat(cid, title, emoji, products):
    return {"id": cid, "title": title, "emoji": emoji, "products": products}


def _base(slug, name, currency, support):
    return {
        "name": name, "slug": slug, "language": "ru", "currency": currency,
        "support_username": support, "token_env": "BOT_TOKEN",
        "admin_env": "ADMIN_IDS", "orders_chat_env": "ORDERS_CHAT_ID",
    }


def digital(slug, name, currency, support, tagline, catalog):
    d = _base(slug, name, currency, support)
    d.update({
        "fulfillment": "digital",
        "welcome": (f"👋 Добро пожаловать в <b>{name}</b>!\n\n{tagline}\n\n"
                    "✅ Оплата картой или криптовалютой\n"
                    "⚡️ Моментальная автоматическая выдача"),
        "rules": RULES_DIGITAL,
        "payments": {
            "telegram_enabled": True, "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True, "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": False, "cod_enabled": False,
        },
        "catalog": catalog,
    })
    return d


def physical(slug, name, currency, support, tagline, catalog, note, service=False):
    d = _base(slug, name, currency, support)
    intro = ("🗓 Выберите услугу\n💳 Оплата картой, криптой или на месте\n"
             "🚗 Мастер приедет к вам") if service else \
            ("🛒 Соберите заказ в корзину\n💳 Оплата картой, криптой или при получении\n"
             "🚚 Доставка по городу")
    d.update({
        "fulfillment": "physical",
        "welcome": f"👋 <b>{name}</b>\n\n{tagline}\n\n{intro}",
        "rules": ("<b>Как это работает</b>\n\n"
                  "1. Выберите позиции и добавьте в корзину.\n"
                  "2. Оформите заказ и укажите адрес.\n"
                  "3. Выберите оплату онлайн или на месте.\n"
                  "4. Мы подтвердим и приедем к вам."),
        "delivery_note": note,
        "payments": {
            "telegram_enabled": True, "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True, "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": False, "cod_enabled": True,
        },
        "catalog": catalog,
    })
    return d


SHOPS = [
    # ------------------------- digital -------------------------
    digital("domains", "DomainHub", "USD", "@domainhub_support",
            "Домены и всё для запуска сайта.", [
        cat("domains", "Домены", "🌐", [
            p("dom_com", "Домен .com (1 год)", 9.00, "Регистрация домена .com на год."),
            p("dom_io", "Домен .io (1 год)", 32.00, "Премиальный домен .io."),
        ]),
        cat("ssl", "SSL и почта", "🔒", [
            p("ssl_dv", "SSL-сертификат DV (1 год)", 7.00, "Шифрование для сайта."),
            p("mail_biz", "Корпоративная почта (1 мес.)", 3.00, "Почта на вашем домене."),
        ]),
    ]),
    digital("business_email", "MailPro", "USD", "@mailpro_support",
            "Бизнес-почта и рассылочные ящики под ключ.", [
        cat("mailboxes", "Почтовые ящики", "📧", [
            p("mail_1", "Почтовый ящик (1 мес.)", 1.50, "Отдельный ящик на вашем домене."),
            p("mail_10", "Пакет 10 ящиков (1 мес.)", 12.00, "Для команды."),
        ]),
        cat("smtp", "SMTP", "📤", [
            p("smtp_basic", "SMTP-релей (10k писем)", 5.00, "Для транзакционных писем."),
        ]),
    ]),
    digital("smm", "BoostPanel", "USD", "@boostpanel_support",
            "SMM-продвижение: подписчики, лайки, просмотры.", [
        cat("followers", "Подписчики", "👥", [
            p("smm_ig_1k", "Instagram — 1000 подписчиков", 4.00, "Плавная накрутка."),
            p("smm_tg_1k", "Telegram — 1000 подписчиков", 3.50, "На канал/группу."),
        ]),
        cat("engagement", "Активность", "❤️", [
            p("smm_likes_1k", "1000 лайков", 2.00, "На пост по ссылке."),
            p("smm_views_10k", "10000 просмотров", 1.50, "На видео/пост."),
        ]),
    ]),
    digital("discord", "NitroShop", "USD", "@nitroshop_support",
            "Discord Nitro и бусты для серверов.", [
        cat("nitro", "Nitro", "🎮", [
            p("nitro_1m", "Discord Nitro (1 мес.)", 4.50, "Полный Nitro на месяц."),
            p("nitro_1y", "Discord Nitro (1 год)", 40.00, "Годовая подписка."),
        ]),
        cat("boosts", "Бусты", "🚀", [
            p("boost_14", "14 бустов (1 мес.)", 12.00, "Максимальный уровень сервера."),
        ]),
    ]),
    digital("music_beats", "BeatStore", "USD", "@beatstore_support",
            "Биты, сэмплы и пресеты для музыкантов.", [
        cat("beats", "Биты", "🎵", [
            p("beat_lease", "Бит (lease-лицензия)", 20.00, "MP3/WAV + права на релиз."),
            p("beat_excl", "Бит (эксклюзив)", 150.00, "Полные права, снимается с продажи."),
        ]),
        cat("samples", "Сэмплы", "🎚", [
            p("sample_pack", "Сэмпл-пак", 12.00, "Набор роялти-фри сэмплов."),
        ]),
    ]),
    digital("stock_media", "StockVault", "USD", "@stockvault_support",
            "Стоковые фото и видео без роялти.", [
        cat("photos", "Фото", "🖼", [
            p("photo_10", "10 фото (пакет)", 5.00, "Роялти-фри изображения в высоком разрешении."),
        ]),
        cat("video", "Видео", "🎬", [
            p("video_clip", "Видеоклип (4K)", 12.00, "Стоковый ролик для проектов."),
            p("video_pack", "Пакет 5 клипов", 45.00, "Со скидкой."),
        ]),
    ]),
    digital("fonts", "FontFoundry", "USD", "@fontfoundry_support",
            "Шрифты и типографика для брендов.", [
        cat("fonts", "Шрифты", "🔤", [
            p("font_single", "Шрифт (1 начертание)", 6.00, "Коммерческая лицензия."),
            p("font_family", "Семейство шрифтов", 20.00, "Все начертания."),
        ]),
    ]),
    digital("wp_themes", "ThemeMarket", "USD", "@thememarket_support",
            "Темы и плагины для WordPress.", [
        cat("themes", "Темы", "🎨", [
            p("theme_business", "Тема «Бизнес»", 15.00, "Готовый сайт-визитка."),
            p("theme_shop", "Тема «Магазин»", 22.00, "WooCommerce-совместимая."),
        ]),
        cat("plugins", "Плагины", "🧩", [
            p("plugin_seo", "SEO-плагин (лицензия)", 9.00, "Продвижение сайта."),
        ]),
    ]),
    digital("mobile_topup", "TopUpGo", "USD", "@topupgo_support",
            "Пополнение мобильных и игровых балансов.", [
        cat("mobile", "Мобильные", "📱", [
            p("topup_5", "Пополнение — $5", 5.00, "Код пополнения баланса."),
            p("topup_10", "Пополнение — $10", 10.00, "Код пополнения баланса."),
        ]),
        cat("gaming", "Игровые", "🎮", [
            p("topup_pubg", "PUBG UC — 660", 10.00, "Код игровой валюты."),
        ]),
    ]),
    digital("trading_edu", "TradeAcademy", "USD", "@tradeacademy_support",
            "Обучение трейдингу и финансовой грамотности.", [
        cat("courses", "Курсы", "📈", [
            p("edu_basics", "Курс «Основы трейдинга»", 25.00, "С нуля до первой сделки."),
            p("edu_ta", "Курс «Технический анализ»", 30.00, "Графики, паттерны, риск-менеджмент."),
        ]),
        cat("materials", "Материалы", "📚", [
            p("edu_ebook", "Книга «Психология рынка»", 8.00, "PDF, мгновенная выдача."),
        ]),
    ]),
    digital("presets", "PresetLab", "USD", "@presetlab_support",
            "Пресеты для обработки фото.", [
        cat("presets", "Пресеты", "🌈", [
            p("preset_pack", "Пакет пресетов Lightroom", 7.00, "10 пресетов + инструкция."),
            p("preset_mobile", "Мобильные пресеты (DNG)", 5.00, "Для Lightroom Mobile."),
        ]),
    ]),
    digital("notion_templates", "NotionKit", "USD", "@notionkit_support",
            "Готовые шаблоны Notion для работы и жизни.", [
        cat("templates", "Шаблоны", "🗂", [
            p("notion_planner", "Планировщик задач", 4.00, "Дублируется в один клик."),
            p("notion_crm", "Мини-CRM", 9.00, "Управление клиентами и сделками."),
        ]),
    ]),
    digital("audiobooks", "AudioShelf", "USD", "@audioshelf_support",
            "Аудиокниги с моментальной выдачей.", [
        cat("business", "Бизнес", "💼", [
            p("ab_business", "Аудиокнига «Бизнес с нуля»", 6.00, "Ссылка на прослушивание в выдаче."),
        ]),
        cat("fiction", "Художественные", "📖", [
            p("ab_fiction", "Аудиокнига (роман)", 5.00, "Полная озвучка."),
        ]),
    ]),
    digital("cloud_storage", "CloudBox", "USD", "@cloudbox_support",
            "Облачное хранилище с выдачей доступа.", [
        cat("plans", "Тарифы", "☁️", [
            p("cloud_100", "100 ГБ (1 мес.)", 2.00, "Доступ приходит после оплаты."),
            p("cloud_1tb", "1 ТБ (1 мес.)", 6.00, "Для больших объёмов."),
        ]),
    ]),
    digital("ai_tools", "AIMarket", "USD", "@aimarket_support",
            "Доступы к AI-инструментам и подпискам.", [
        cat("subs", "Подписки", "🤖", [
            p("ai_chat_1m", "AI-чат Pro (1 мес.)", 12.00, "Доступ к продвинутой модели."),
            p("ai_image_1m", "AI-генерация изображений (1 мес.)", 9.00, "Пакет генераций."),
        ]),
    ]),
    digital("app_templates", "AppForge", "USD", "@appforge_support",
            "Исходники и шаблоны мобильных приложений.", [
        cat("templates", "Шаблоны", "📲", [
            p("app_shop", "Шаблон «Магазин» (Flutter)", 35.00, "Исходники + инструкция сборки."),
            p("app_delivery", "Шаблон «Доставка»", 40.00, "Готовый UI и логика."),
        ]),
    ]),
    digital("seo_tools", "SEOKit", "USD", "@seokit_support",
            "Инструменты и доступы для SEO.", [
        cat("access", "Доступы", "🔎", [
            p("seo_analytics_1m", "SEO-аналитика (1 мес.)", 10.00, "Доступ к платформе."),
            p("seo_backlinks", "Пакет ссылок (10 шт.)", 15.00, "Качественные бэклинки."),
        ]),
    ]),
    digital("mystery_box", "LootBox", "USD", "@lootbox_support",
            "Цифровые mystery-box: случайный приз внутри!", [
        cat("boxes", "Боксы", "🎁", [
            p("box_small", "Mystery Box — Small", 3.00, "Случайный цифровой приз (ключ/промокод/подписка)."),
            p("box_big", "Mystery Box — Big", 10.00, "Приз повышенной ценности гарантирован."),
        ]),
    ]),

    # ------------------------- physical (delivery) -------------------------
    physical("pizza", "PizzaExpress", "RUB", "@pizzaexpress_support",
             "Пицца из дровяной печи с доставкой.", [
        cat("pizza", "Пицца", "🍕", [
            p("pizza_margarita", "Маргарита", 490, "Томаты, моцарелла, базилик. 30 см."),
            p("pizza_pepperoni", "Пепперони", 590, "Острая колбаса, сыр. 30 см."),
            p("pizza_four_cheese", "4 сыра", 620, "Моцарелла, дорблю, пармезан, чеддер."),
        ]),
        cat("drinks", "Напитки", "🥤", [
            p("cola05", "Cola 0.5", 120, ""), p("juice", "Сок 0.3", 110, ""),
        ]),
    ], note="Доставка 45–75 минут. Минимальный заказ — 600 ₽."),
    physical("coffee", "CoffeeGo", "RUB", "@coffeego_support",
             "Свежий кофе и десерты к двери.", [
        cat("coffee", "Кофе", "☕️", [
            p("latte", "Латте", 190, "На выбор молоко."),
            p("cappuccino", "Капучино", 180, ""),
            p("americano", "Американо", 150, ""),
        ]),
        cat("desserts", "Десерты", "🍰", [
            p("cheesecake", "Чизкейк", 250, ""), p("croissant", "Круассан", 130, ""),
        ]),
    ], note="Доставка по центру города, 30–60 минут."),
    physical("flowers", "FloraBox", "RUB", "@florabox_support",
             "Букеты и цветы с доставкой в день заказа.", [
        cat("bouquets", "Букеты", "💐", [
            p("bouq_roses", "Букет из 25 роз", 2500, "Свежие розы, оформление."),
            p("bouq_mix", "Авторский микс", 1900, "Сезонные цветы."),
        ]),
        cat("addons", "Дополнения", "🎀", [
            p("card", "Открытка с текстом", 100, ""), p("vase", "Ваза", 500, ""),
        ]),
    ], note="Доставка в течение дня. Фото букета перед отправкой."),
    physical("cakes", "SweetBakery", "RUB", "@sweetbakery_support",
             "Торты и выпечка на заказ.", [
        cat("cakes", "Торты", "🎂", [
            p("cake_choco", "Шоколадный торт (1 кг)", 1400, "На заказ, за сутки."),
            p("cake_fruit", "Фруктовый торт (1 кг)", 1500, ""),
        ]),
        cat("pastry", "Выпечка", "🥐", [
            p("eclair", "Эклеры (6 шт.)", 400, ""), p("macarons", "Макаронс (6 шт.)", 500, ""),
        ]),
    ], note="Торты — предзаказ за 24 часа."),
    physical("groceries", "FreshMarket", "RUB", "@freshmarket_support",
             "Продукты с доставкой за час.", [
        cat("fresh", "Свежее", "🥦", [
            p("veg_set", "Овощной набор", 450, "Сезонные овощи, 3–4 кг."),
            p("fruit_set", "Фруктовый набор", 550, ""),
        ]),
        cat("dairy", "Молочное", "🥛", [
            p("milk", "Молоко 1 л", 90, ""), p("eggs", "Яйца (10 шт.)", 110, ""),
        ]),
    ], note="Доставка 60–120 минут. Минимальный заказ — 500 ₽."),
    physical("merch", "MerchLab", "USD", "@merchlab_support",
             "Мерч и одежда с печатью.", [
        cat("apparel", "Одежда", "👕", [
            p("tshirt", "Футболка с принтом", 20, "Хлопок, размеры S–XXL."),
            p("hoodie", "Худи с принтом", 45, ""),
        ]),
        cat("accessories", "Аксессуары", "🧢", [
            p("cap", "Кепка", 18, ""), p("mug", "Кружка", 12, ""),
        ]),
    ], note="Печать 2–4 дня, затем доставка."),
    physical("sneakers", "SneakerSpot", "USD", "@sneakerspot_support",
             "Кроссовки и обувь с доставкой.", [
        cat("sneakers", "Кроссовки", "👟", [
            p("sneaker_run", "Беговые кроссовки", 75, "Размеры 38–46."),
            p("sneaker_casual", "Повседневные кеды", 55, ""),
        ]),
    ], note="Укажите размер в комментарии к заказу."),
    physical("electronics", "GadgetStore", "USD", "@gadgetstore_support",
             "Гаджеты и аксессуары.", [
        cat("audio", "Аудио", "🎧", [
            p("earbuds", "Беспроводные наушники", 30, ""),
            p("speaker", "Портативная колонка", 40, ""),
        ]),
        cat("accessories", "Аксессуары", "🔌", [
            p("powerbank", "Повербанк 10000 мА·ч", 22, ""), p("cable", "Кабель USB-C", 8, ""),
        ]),
    ], note="Гарантия 12 месяцев на технику."),
    physical("gift_boxes", "GiftCraft", "USD", "@giftcraft_support",
             "Подарочные боксы ручной сборки.", [
        cat("boxes", "Боксы", "🎁", [
            p("box_him", "Бокс «Для него»", 35, "Уходовая косметика, аксессуары."),
            p("box_her", "Бокс «Для неё»", 35, ""),
        ]),
    ], note="Соберём и доставим с открыткой."),

    # ------------------------- on-location services -------------------------
    physical("barbershop", "BarberBook", "RUB", "@barberbook_support",
             "Выездной барбер: стрижка у вас дома или в офисе.", [
        cat("services", "Услуги", "💈", [
            p("cut", "Мужская стрижка", 1200, "Мастер приедет к вам."),
            p("beard", "Оформление бороды", 700, ""),
            p("cut_beard", "Стрижка + борода", 1700, "Комплекс."),
        ]),
    ], note="Мастер свяжется для подтверждения времени.", service=True),
    physical("cleaning", "CleanPro", "RUB", "@cleanpro_support",
             "Клининг: уборка квартир и офисов.", [
        cat("services", "Услуги", "🧼", [
            p("clean_studio", "Уборка студии", 2000, "До 30 м²."),
            p("clean_2room", "Уборка 2-комн.", 3500, ""),
            p("clean_office", "Уборка офиса (м²)", 60, "Цена за м², от 50 м²."),
        ]),
    ], note="Оставьте адрес и удобное время — подтвердим заказ.", service=True),
    physical("carwash", "WashGo", "RUB", "@washgo_support",
             "Выездная мойка авто у вас на месте.", [
        cat("services", "Услуги", "🚗", [
            p("wash_body", "Мойка кузова", 800, "Приедем к вам."),
            p("wash_full", "Комплекс (кузов + салон)", 1800, ""),
        ]),
    ], note="Нужен доступ к воде/парковке. Подтвердим время.", service=True),
]


def main():
    os.makedirs(OUT, exist_ok=True)
    for data in SHOPS:
        path = os.path.join(OUT, f"{data['slug']}.yaml")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(name=data["name"]))
            yaml.safe_dump(data, fh, allow_unicode=True, sort_keys=False, width=100)
        print("wrote", path)
    print(f"total new: {len(SHOPS)}")


if __name__ == "__main__":
    main()
