#!/usr/bin/env python3
"""Mass-generate configs to reach 1000 bots: +390 Telegram-account shops and
+510 other shops (weighted toward the most profitable / highest-ticket niches).

Same tested core; only data differs. Brand names are combined from an adjective
list x per-niche nouns, and every price is deterministically jittered so
replicas are not literally identical. Run:

    python tools/gen_mass.py
"""
from __future__ import annotations

import os

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "config")

HEADER = (
    "# ---------------------------------------------------------------------------\n"
    "# {name}\n"
    "# Generated by tools/gen_mass.py. Secrets come from env/.env.\n"
    "# ---------------------------------------------------------------------------\n"
)

N_TG = 390
N_OTHER = 510

ADJ = ["Pro", "Prime", "Elite", "Turbo", "Mega", "Grand", "Royal", "Smart",
       "Rapid", "Global", "Alpha", "Nova", "Hyper", "Ultra", "Max", "Neo",
       "Apex", "Vault", "Swift", "Titan", "Lucky", "First", "Direct", "Instant",
       "Cyber", "Digital", "Trust", "Fast", "Top", "Star"]

RULES_D = ("<b>Правила магазина</b>\n\n"
           "• Цифровой товар возврату не подлежит после выдачи.\n"
           "• Проверяйте товар сразу после получения.\n"
           "• Брак заменяем по обращению в поддержку.")


def jitter(base: float, i: int) -> float:
    f = 0.80 + ((i * 37) % 41) / 100.0   # 0.80 .. 1.20, deterministic
    v = base * f
    return round(v, 2) if v < 100 else round(v)


def brand(nouns, i: int) -> str:
    return f"{ADJ[i % len(ADJ)]} {nouns[(i // len(ADJ)) % len(nouns)]}"


def p(sku, title, price, desc=""):
    return {"sku": sku, "title": title, "price": price, "description": desc}


def cat(cid, title, emoji, products):
    return {"id": cid, "title": title, "emoji": emoji, "products": products}


def _base(slug, name, currency, support):
    return {"name": name, "slug": slug, "language": "ru", "currency": currency,
            "support_username": support, "token_env": "BOT_TOKEN",
            "admin_env": "ADMIN_IDS", "orders_chat_env": "ORDERS_CHAT_ID"}


def _pay(cod=False):
    return {"telegram_enabled": True, "telegram_provider_token_env": "PROVIDER_TOKEN",
            "cryptobot_enabled": True, "cryptobot_token_env": "CRYPTOBOT_TOKEN",
            "cryptobot_testnet": False, "cod_enabled": cod}


def make_digital(slug, name, currency, tagline, catalog):
    d = _base(slug, name, currency, f"@{slug}_support")
    d.update({"fulfillment": "digital",
              "welcome": (f"👋 Добро пожаловать в <b>{name}</b>!\n\n{tagline}\n\n"
                          "✅ Оплата картой или криптовалютой\n"
                          "⚡️ Моментальная автоматическая выдача"),
              "rules": RULES_D, "payments": _pay(False), "catalog": catalog})
    return d


def make_physical(slug, name, currency, tagline, catalog):
    d = _base(slug, name, currency, f"@{slug}_support")
    d.update({"fulfillment": "physical",
              "welcome": (f"👋 <b>{name}</b>\n\n{tagline}\n\n"
                          "🛒 Соберите заказ · 💳 карта/крипта/при получении · 🚚 доставка"),
              "rules": ("<b>Как это работает</b>\n\n1. Добавьте в корзину.\n"
                        "2. Оформите заказ и укажите адрес.\n"
                        "3. Оплатите онлайн или на месте.\n4. Мы подтвердим и привезём."),
              "delivery_note": "Уточним детали после оформления заказа.",
              "payments": _pay(True), "catalog": catalog})
    return d


# --------------------------- Telegram-account shops ---------------------------
TG_NOUNS = ["Telega", "TG Store", "TG Market", "Аккаунты", "Numbers", "Sessions",
            "TG Hub", "Telemarket", "AccStore", "TG Vault"]


def tg_catalog(i):
    return [
        cat("virtual", "Виртуальные аккаунты", "📱", [
            p("virt_us", "Аккаунт (US) — виртуальный номер", jitter(3.5, i), "Свежая регистрация, моментальная выдача."),
            p("virt_eu", "Аккаунт (EU) — виртуальный номер", jitter(4.0, i)),
            p("virt_asia", "Аккаунт (Asia) — виртуальный", jitter(2.8, i)),
        ]),
        cat("aged", "Отлежавшиеся аккаунты", "🧊", [
            p("aged_6m", "Аккаунт с отлёжкой 6+ мес.", jitter(6.0, i)),
            p("aged_1y", "Аккаунт с отлёжкой 1+ год", jitter(9.0, i)),
        ]),
        cat("premium", "Премиум и сессии", "💎", [
            p("prem_1m", "Аккаунт с Telegram Premium (1 мес.)", jitter(8.5, i)),
            p("tdata", "TData-сессия", jitter(5.0, i)),
        ]),
    ]


# --------------------------- other niches (archetypes) ---------------------------
# (key, nouns, fulfillment, currency, weight, catalog-spec, tagline)
# catalog-spec: [(cat_id, title, emoji, [(sku, label, base_price), ...]), ...]
ARCHES = [
    ("wa", ["WhatsApp", "WA Shop", "Messenger"], "d", "USD", 26,
     [("acc", "Аккаунты", "🟢", [("fresh", "WhatsApp — свежий", 2.5), ("aged", "WhatsApp — с отлёжкой", 5.0), ("bulk", "WhatsApp — пакет 10 шт.", 22.0)])],
     "Аккаунты WhatsApp для работы и рассылок."),
    ("ig", ["Instagram", "Insta Shop", "IG Market"], "d", "USD", 26,
     [("acc", "Аккаунты", "📸", [("fresh", "Instagram — свежий", 2.0), ("aged", "Instagram — с отлёжкой", 5.0), ("verified", "Instagram — с подписчиками", 20.0)])],
     "Аккаунты Instagram для продвижения."),
    ("fb", ["Facebook", "FB Shop", "Meta Market"], "d", "USD", 24,
     [("acc", "Аккаунты", "🔵", [("fresh", "Facebook — свежий", 2.0), ("aged", "Facebook — с отлёжкой", 6.0), ("farm", "Facebook — фарм-аккаунт", 25.0)])],
     "Аккаунты Facebook под любые задачи."),
    ("goog", ["Google", "Gmail Shop", "Acc Market"], "d", "USD", 22,
     [("acc", "Аккаунты", "📧", [("fresh", "Google — свежий", 1.5), ("aged", "Google — с отлёжкой", 4.0), ("aged2y", "Google — 2+ года", 9.0)])],
     "Google/Gmail аккаунты."),
    ("ads", ["Ad Accounts", "Ads Market", "Ad Vault"], "d", "USD", 24,
     [("ads", "Рекламные кабинеты", "📣", [("fb_agency", "Facebook Ads (агентский)", 60.0), ("google_ads", "Google Ads кабинет", 55.0), ("tiktok_ads", "TikTok Ads кабинет", 70.0)])],
     "Рекламные кабинеты с лимитами."),
    ("verified", ["Verified", "Blue Shop", "Verify Market"], "d", "USD", 20,
     [("v", "Верификация", "✅", [("ig_blue", "Instagram — синяя галочка", 25.0), ("tg_prem", "Telegram Premium", 12.0), ("business", "Бизнес-аккаунт", 40.0)])],
     "Верифицированные и бизнес-аккаунты."),
    ("soft", ["Software Keys", "Key Shop", "License Market"], "d", "USD", 24,
     [("os", "ОС", "🪟", [("win11", "Windows 11 Pro", 12.0), ("win10", "Windows 10 Pro", 10.0)]),
      ("apps", "Приложения", "🎨", [("office", "Office 2021", 18.0), ("adobe", "Adobe (1 мес.)", 15.0)])],
     "Лицензионные ключи для ПО."),
    ("host", ["VPS Hosting", "Cloud Node", "Host Market"], "d", "USD", 22,
     [("vps", "VPS/RDP", "🖥", [("vps_s", "VPS Start", 5.0), ("vps_l", "VPS Pro", 12.0), ("rdp", "RDP-доступ", 8.0)])],
     "VPS, RDP и хостинг с моментальной выдачей."),
    ("vpn", ["VPN", "VPN Shop", "Secure Net"], "d", "USD", 20,
     [("plans", "Подписки", "🔐", [("m1", "VPN — 1 месяц", 3.0), ("y1", "VPN — 1 год", 25.0), ("dedic", "Выделенный IP", 7.0)])],
     "Быстрый и безопасный VPN."),
    ("prox", ["Proxies", "Proxy Hub", "IP Market"], "d", "USD", 20,
     [("dc", "Датацентр", "🌐", [("ipv4", "IPv4 прокси (30 дн.)", 2.0), ("resid", "Резидентные — 1 ГБ", 5.0), ("mobile", "Мобильный прокси (7 дн.)", 8.0)])],
     "Приватные, резидентные и мобильные прокси."),
    ("tradeedu", ["Trading Signals", "Trade Academy", "Invest Club"], "d", "USD", 22,
     [("edu", "Обучение и сигналы", "📈", [("signals_1m", "Сигналы (1 мес.)", 30.0), ("course", "Курс по трейдингу", 40.0), ("vip", "VIP-подписка", 90.0)])],
     "Обучение трейдингу и торговые сигналы."),
    ("course", ["Courses", "Skill Rise", "Edu Market"], "d", "USD", 20,
     [("courses", "Курсы", "🎓", [("basic", "Курс (самостоятельно)", 20.0), ("mentor", "Курс с наставником", 45.0), ("career", "Курс + трудоустройство", 60.0)])],
     "Онлайн-курсы с доступом сразу."),
    ("gift", ["Gift Cards", "Gift Zone", "Card Market"], "d", "USD", 18,
     [("cards", "Карты", "🎁", [("amazon25", "Amazon — $25", 24.0), ("steam20", "Steam — $20", 19.5), ("apple15", "App Store — $15", 14.5)])],
     "Подарочные карты и коды пополнения."),
    ("gameacc", ["Game Accounts", "Game Vault", "Play Market"], "d", "USD", 18,
     [("acc", "Аккаунты", "🎮", [("steam", "Steam-аккаунт", 3.0), ("fresh", "Игровой аккаунт (свежий)", 8.0), ("loaded", "Аккаунт с играми", 25.0)])],
     "Игровые аккаунты и ключи."),
    ("smm", ["SMM Panel", "Boost Panel", "Promo Market"], "d", "USD", 18,
     [("smm", "Продвижение", "🚀", [("followers", "1000 подписчиков", 4.0), ("likes", "1000 лайков", 2.0), ("views", "10000 просмотров", 1.5)])],
     "SMM: подписчики, лайки, просмотры."),
    ("esim", ["eSIM", "eSIM Go", "Travel Net"], "d", "EUR", 12,
     [("esim", "eSIM", "✈️", [("eu5", "Европа — 5 ГБ", 12.0), ("glob3", "Мир — 3 ГБ", 15.0)])],
     "eSIM для поездок и виртуальные номера."),
    ("mail", ["Email SMTP", "Mail Pro", "SMTP Shop"], "d", "USD", 12,
     [("mail", "Почта и SMTP", "📤", [("box", "Почтовый ящик (1 мес.)", 1.5), ("smtp", "SMTP-релей (10k)", 5.0)])],
     "Бизнес-почта и SMTP."),
    ("ai", ["AI Tools", "AI Market", "Neuro Shop"], "d", "USD", 14,
     [("ai", "Подписки", "🤖", [("chat", "AI-чат Pro (1 мес.)", 12.0), ("image", "AI-картинки (1 мес.)", 9.0)])],
     "Доступы к AI-инструментам."),
    ("dom", ["Domains", "Domain Hub", "Name Market"], "d", "USD", 12,
     [("dom", "Домены", "🏷", [("com", "Домен .com (1 год)", 9.0), ("io", "Домен .io (1 год)", 32.0)])],
     "Домены и всё для запуска сайта."),
    ("seo", ["SEO Tools", "SEO Kit", "Rank Shop"], "d", "USD", 12,
     [("seo", "SEO", "🔎", [("analytics", "SEO-аналитика (1 мес.)", 10.0), ("backlinks", "Пакет ссылок (10 шт.)", 15.0)])],
     "Инструменты и услуги SEO."),
    ("design", ["Logo Design", "Design Lab", "Brand Studio"], "d", "USD", 12,
     [("logo", "Логотипы", "🎨", [("basic", "Логотип Basic", 25.0), ("pro", "Логотип Pro", 60.0)])],
     "Дизайн логотипа под ключ."),
    ("content", ["Copywriting", "Text Craft", "Content Shop"], "d", "USD", 10,
     [("text", "Тексты", "📝", [("post", "Пост для соцсетей", 5.0), ("landing", "Текст для лендинга", 30.0)])],
     "Тексты и копирайтинг."),
    ("video", ["Video Editing", "Cut Studio", "Edit Market"], "d", "USD", 10,
     [("edit", "Монтаж", "🎞", [("reel", "Reels/Shorts", 12.0), ("long", "Видео до 10 мин", 45.0)])],
     "Монтаж видео для соцсетей."),
    ("saas", ["SaaS Access", "Soft Hub", "Tools Market"], "d", "USD", 12,
     [("saas", "Доступы", "📊", [("crm", "CRM (1 мес.)", 9.0), ("pm", "Планировщик (1 мес.)", 12.0)])],
     "Доступ к SaaS-инструментам."),
    ("media", ["Design Assets", "Pixel Market", "Asset Shop"], "d", "USD", 10,
     [("assets", "Ассеты", "🖼", [("icons", "Набор иконок", 5.0), ("uikit", "UI-kit", 12.0)])],
     "Готовые дизайн-ассеты и шаблоны."),
    ("websites", ["Website Dev", "Web Studio", "Site Craft"], "d", "USD", 12,
     [("web", "Разработка", "💻", [("landing", "Лендинг под ключ", 60.0), ("corporate", "Корпоративный сайт", 150.0)])],
     "Сайты и лендинги под ключ."),
    ("branding", ["Branding", "Brand Lab", "Identity Studio"], "d", "USD", 10,
     [("brand", "Брендинг", "✨", [("logo", "Логотип + гайд", 60.0), ("identity", "Айдентика под ключ", 150.0)])],
     "Брендинг и фирменный стиль."),
    ("marketing", ["Marketing", "Growth Agency", "Promo Studio"], "d", "USD", 10,
     [("mkt", "Маркетинг", "📈", [("smm_month", "Ведение соцсетей (мес.)", 120.0), ("ads_setup", "Настройка рекламы", 90.0)])],
     "Маркетинг и продвижение под ключ."),
    ("consulting", ["Consulting", "Expert Hub", "Advisor"], "d", "USD", 8,
     [("cons", "Консультации", "💼", [("hour", "Консультация (час)", 50.0), ("package", "Пакет сопровождения", 300.0)])],
     "Экспертные консультации."),

    # ---- physical goods (RUB unless noted) ----
    ("pizza", ["Pizza", "Pizza Express", "Slice House"], "p", "RUB", 10,
     [("pizza", "Пицца", "🍕", [("margarita", "Маргарита", 490.0), ("pepperoni", "Пепперони", 590.0)])],
     "Пицца из печи с доставкой."),
    ("sushi", ["Sushi", "Sushi Time", "Roll House"], "p", "RUB", 10,
     [("sushi", "Роллы и сеты", "🍣", [("phil", "Филадельфия", 380.0), ("set", "Суши-сет (30 шт.)", 990.0)])],
     "Суши и роллы с доставкой."),
    ("burger", ["Burgers", "Burger House", "Grill Bun"], "p", "RUB", 8,
     [("burger", "Бургеры", "🍔", [("cheese", "Чизбургер", 320.0), ("double", "Двойной бургер", 420.0)])],
     "Бургеры на гриле с доставкой."),
    ("coffee", ["Coffee", "Coffee Go", "Bean Bar"], "p", "RUB", 8,
     [("coffee", "Кофе", "☕️", [("latte", "Латте", 190.0), ("set", "Кофе + десерт", 350.0)])],
     "Кофе и десерты к двери."),
    ("flowers", ["Flowers", "Flora Box", "Bloom Shop"], "p", "RUB", 8,
     [("bouquets", "Букеты", "💐", [("roses25", "Букет из 25 роз", 2500.0), ("mix", "Авторский микс", 1900.0)])],
     "Букеты с доставкой в день заказа."),
    ("sweets", ["Cakes", "Sweet Bakery", "Cake House"], "p", "RUB", 6,
     [("cakes", "Торты", "🎂", [("choco", "Шоколадный торт (1 кг)", 1400.0), ("eclair", "Эклеры (6 шт.)", 400.0)])],
     "Торты и выпечка на заказ."),
    ("grocery", ["Groceries", "Fresh Market", "Daily Shop"], "p", "RUB", 6,
     [("fresh", "Продукты", "🥦", [("veg", "Овощной набор", 450.0), ("dairy", "Молочный набор", 300.0)])],
     "Продукты с доставкой за час."),
    ("fashion", ["Sneakers", "Sneaker Spot", "Shoe Store"], "p", "USD", 6,
     [("sneakers", "Обувь", "👟", [("run", "Беговые кроссовки", 75.0), ("casual", "Кеды", 55.0)])],
     "Кроссовки и обувь с доставкой."),
    ("electro", ["Electronics", "Gadget Store", "Tech Shop"], "p", "USD", 6,
     [("audio", "Гаджеты", "🎧", [("earbuds", "Наушники", 30.0), ("powerbank", "Повербанк", 22.0)])],
     "Гаджеты и аксессуары."),

    # ---- physical services (RUB) ----
    ("clean", ["Cleaning", "Clean Pro", "Sparkle"], "p", "RUB", 8,
     [("services", "Уборка", "🧼", [("studio", "Уборка студии", 2000.0), ("office", "Уборка офиса (м²)", 60.0)])],
     "Клининг квартир и офисов."),
    ("barber", ["Barber", "Barber Book", "Sharp Cut"], "p", "RUB", 8,
     [("services", "Услуги", "💈", [("cut", "Мужская стрижка", 1200.0), ("combo", "Стрижка + борода", 1700.0)])],
     "Барбершоп / выездной барбер."),
    ("massage", ["Massage", "Massage Book", "Relax Studio"], "p", "RUB", 6,
     [("services", "Услуги", "💆", [("relax", "Релакс-массаж (60 мин)", 2500.0), ("back", "Массаж спины", 1500.0)])],
     "Выездной массаж у вас дома."),
    ("courier", ["Courier", "Courier Go", "Fast Delivery"], "p", "RUB", 6,
     [("services", "Услуги", "🛵", [("city", "Доставка по городу", 300.0), ("express", "Экспресс", 500.0)])],
     "Курьерская доставка по городу."),
]


def build_catalog(spec, i):
    return [cat(cid, title, emoji,
               [p(f"{cid}_{sku}", label, jitter(price, i + n), "")
                for n, (sku, label, price) in enumerate(products)])
            for cid, title, emoji, products in spec]


def main():
    os.makedirs(OUT, exist_ok=True)
    written = 0

    # --- 390 Telegram-account shops ---
    for i in range(1, N_TG + 1):
        slug = f"tg_m{i:03d}"
        name = brand(TG_NOUNS, i)
        cur = ["USD", "RUB", "USD", "EUR", "RUB"][i % 5]
        data = make_digital(slug, name, cur,
                            "Магазин Telegram-аккаунтов: виртуалки, отлёжка, премиум.",
                            tg_catalog(i))
        _write(slug, data)
        written += 1

    # --- 510 other shops, weighted round-robin over archetypes ---
    weighted = []
    for a in ARCHES:
        weighted += [a] * a[4]
    counters: dict[str, int] = {}
    made = 0
    j = 0
    while made < N_OTHER:
        key, nouns, ful, cur, _w, spec, tagline = weighted[j % len(weighted)]
        j += 1
        idx = counters.get(key, 0) + 1
        counters[key] = idx
        slug = f"{key}_{idx:03d}"
        name = brand(nouns, idx)
        catalog = build_catalog(spec, made)
        if ful == "d":
            data = make_digital(slug, name, cur, tagline, catalog)
        else:
            data = make_physical(slug, name, cur, tagline, catalog)
        _write(slug, data)
        written += 1
        made += 1

    print(f"wrote {written} configs ({N_TG} TG + {N_OTHER} other)")


def _write(slug, data):
    path = os.path.join(OUT, f"{slug}.yaml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(HEADER.format(name=data["name"]))
        yaml.safe_dump(data, fh, allow_unicode=True, sort_keys=False, width=100)


if __name__ == "__main__":
    main()
