#!/usr/bin/env python3
"""Generate docker-compose.yml covering every bot in config/.

One shared image; each service just points at its own config file and its own
env file (env/<slug>.env). Re-run whenever you add or remove a config.

    python tools/gen_compose.py
"""
from __future__ import annotations

import glob
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """# ---------------------------------------------------------------------------
# Auto-generated by tools/gen_compose.py — do not edit by hand.
# Each bot needs its own secrets in env/<slug>.env (copy from env/example.env).
# Bring everything up with:   docker compose up -d --build
# Bring one bot up with:      docker compose up -d tg_accounts_01
# ---------------------------------------------------------------------------

x-bot: &bot
  build:
    context: .
    dockerfile: deploy/Dockerfile
  image: senerztg-shopbot:latest
  restart: unless-stopped
  stop_grace_period: 20s
  volumes:
    - ./data:/app/data
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
"""

SERVICE = """  {slug}:
    <<: *bot
    container_name: bot_{slug}
    command: ["--config", "config/{slug}.yaml"]
    env_file:
      - env/{slug}.env
"""


def main():
    slugs = sorted(
        os.path.splitext(os.path.basename(p))[0]
        for p in glob.glob(os.path.join(HERE, "config", "*.yaml"))
    )
    out = [HEADER]
    for slug in slugs:
        out.append(SERVICE.format(slug=slug))
    path = os.path.join(HERE, "docker-compose.yml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {path} with {len(slugs)} services")


if __name__ == "__main__":
    main()
